apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: bhupi
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: ubuntu
            name: bhupi
            command: ["/bin/bash", "-c", "echo This is a test script; sleep 5"]
          restartPolicy: Never
