kind: Pod
apiVersion: v1
metadata:
  name: label
  labels:                                                   
    env: development
    class: pods
spec:
    containers:
       - name: c00
         image: ubuntu
         command: ["/bin/bash", "-c", "while true; do echo This is a test script; sleep 5 ; done"]