kind: Pod
apiVersion: v1
metadata:
  name: node-selector
  labels:
    env: development
spec:
    containers:
       - name: c00
         image: ubuntu
         command: ["/bin/bash", "-c", "while true; do echo This is a test script; sleep 5 ; done"]
    nodeSelector:                                         
       hardware: t2-medium