kind: Pod                              
apiVersion: v1                     
metadata:                           
  name: Pod                  
spec:                                    
  containers:                      
    - name: c00                     
      image: ubuntu              
      command: ["/bin/bash", "-c", "while true; do echo This is test script; sleep 5 ; done"]
  restartPolicy: Never 