kind: ReplicaSet                                    
apiVersion: apps/v1                            
metadata:
  name: replica-set
spec:
  replicas: 2  
  selector:                  
    matchExpressions:                             # these must match the labels
      - {key: myname, operator: In, values: [Agrawal, Aggarwal, Agarwal]}
      - {key: env, operator: NotIn, values: [production]}
  template:      
    metadata:
      name: testpod7
      labels:              
        myname: Mridul
    spec:
     containers:
       - name: c00
         image: ubuntu
         command: ["/bin/bash", "-c", "while true; do echo This is a test script; sleep 5 ; done"]